# Generated by Django 4.2 on 2023-05-20 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_of_creation',), 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='header',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='содержимое'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликована ли статья?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(default='posts/nophoto.png', upload_to='posts/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
