# Generated by Django 4.2.1 on 2023-06-08 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='дата создания'),
        ),
    ]
