# Generated by Django 4.2.1 on 2023-06-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_date_of_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_of_creation',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
