# Generated by Django 4.2.1 on 2023-06-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_of_creation',), 'permissions': [('can_unpublish_product', 'Can unpublished product'), ('can_change_description_any_product', 'Can change the description of any product'), ('can_change_category_any_product', 'Can change the category of any product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='продукт опубликован'),
        ),
    ]
